# Generated by Django 4.2.7 on 2026-01-30 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview_data', '0001_initial'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_url', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('screenshot_number', models.IntegerField(default=1)),
                ('multiple_people_detected', models.BooleanField(default=False)),
                ('face_count', models.IntegerField(default=0)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('issue_type', models.CharField(blank=True, choices=[('multiple_people', 'Multiple People'), ('no_face', 'No Face'), ('looking_away', 'Looking Away'), ('phone_detected', 'Phone Detected')], max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='interviews.interview')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='interview_data.interviewdata')),
            ],
            options={
                'db_table': 'interview_screenshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['interview', 'timestamp'], name='interview_s_intervi_d50ce9_idx'), models.Index(fields=['session'], name='interview_s_session_47c31c_idx')],
            },
        ),
    ]
