# Generated by Django 4.2.7 on 2026-02-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_interviews', to='users.user'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to='users.user'),
        ),
    ]
