# Generated by Django 4.2.7 on 2026-01-29 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_number', models.IntegerField(default=1)),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url_opened_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('candidate_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('candidate_location', models.CharField(blank=True, max_length=255, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('is_primary_session', models.BooleanField(default=False)),
                ('network_interruptions', models.IntegerField(default=0)),
                ('questions_answered', models.IntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('session_quality_score', models.IntegerField(blank=True, null=True)),
                ('audio_quality', models.IntegerField(blank=True, null=True)),
                ('video_quality', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='interviews.interview')),
            ],
            options={
                'db_table': 'interview_data',
                'ordering': ['-created_at'],
                'unique_together': {('interview', 'session_number')},
            },
        ),
    ]
