# Generated by Django 5.2.3 on 2026-03-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('interview_scheduled', 'Interview Scheduled'), ('interview_started', 'Interview Started'), ('interview_completed', 'Interview Completed'), ('interview_cancelled', 'Interview Cancelled'), ('interview_reminder', 'Interview Reminder'), ('result_available', 'Result Available'), ('job_created', 'Job Created'), ('job_updated', 'Job Updated'), ('candidate_registered', 'Candidate Registered'), ('candidate_added', 'Candidate Added'), ('application_received', 'Application Received'), ('application_status_changed', 'Application Status Changed'), ('agent_created', 'Agent Created'), ('system_announcement', 'System Announcement')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
    ]
